from pathlib import Path

p = Path('index.html')
s = p.read_text(encoding='utf-8')

s = s.replace('<p class="hero-kicker">Sistema operacional e financeiro</p>', '<p class="hero-kicker">Sistema operacional de crédito e financeiro para o mercado imobiliário</p>')
s = s.replace('Simule, analise e aprove crédito <em>em segundos</em>. Automatize sua régua de cobrança com IA 24/7.', 'Simule, solicite e acompanhe crédito <em>de ponta a ponta</em>. Automatize contratos e cobrança com IA.')
s = s.replace('Uma <span class="underline-wrap">plataforma de IA</span> para análise de crédito, contratos, recebíveis e cobrança.', 'Para incorporadoras, construtoras e imobiliárias que precisam vender, financiar e cobrar sem perder a visão da operação.')
s = s.replace('Testar agora!', 'Criar minha conta')
s = s.replace('<div class="hero-meta">Os maiores bancos · Cobrança automática da carteira · Sem fidelidade</div>', '<div class="hero-meta">CRM de crédito · CORBAN AI · Credituz Score · Contratos · Cobrança · Sem fidelidade</div>')

css = '''<style>
.proof-strip{padding:34px 24px;background:#fff;border-top:1px solid var(--gray-soft);border-bottom:1px solid var(--gray-soft)}
.proof-strip-inner{max-width:1050px;margin:0 auto;display:grid;grid-template-columns:.72fr 1.28fr;gap:30px;align-items:center}
.proof-kicker{font-size:14px;font-weight:650;color:var(--lime);margin-bottom:8px}.proof-strip h2{font-size:clamp(25px,3.5vw,36px);margin:0}.proof-quote{font-size:clamp(18px,2.2vw,24px);letter-spacing:-.025em;line-height:1.3}.proof-person{margin-top:10px;color:var(--gray-2);font-size:13px}.proof-link{display:inline-block;margin-top:12px;color:var(--lime);text-decoration:none;font-weight:650;font-size:14px}
.entry-choice{padding:84px 24px;background:var(--paper-warm)}.entry-choice-inner{max-width:1050px;margin:0 auto}.entry-head{text-align:center;max-width:760px;margin:0 auto 34px}.entry-head h2{font-size:clamp(32px,5vw,50px)}.entry-head p{color:var(--gray-2);margin-top:12px}.entry-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.entry-card{background:#fff;border:1px solid var(--gray-soft);border-radius:24px;padding:30px}.entry-card.featured{border-color:#98c8ff;box-shadow:0 0 0 3px rgba(0,113,227,.06)}.entry-tag{font-size:13px;font-weight:650;color:var(--lime)}.entry-card h3{font-size:28px;margin:8px 0}.entry-price{font-size:36px;font-weight:700;letter-spacing:-.04em}.entry-price small{font-size:14px;font-weight:500;color:var(--gray-2)}.entry-card p{color:var(--gray-2);margin:12px 0 18px}.entry-list{list-style:none;margin:0 0 22px;padding:0}.entry-list li{padding:6px 0;font-size:14px}.entry-list li:before{content:'✓';color:var(--good);font-weight:700;margin-right:8px}.entry-btn{display:inline-flex;padding:12px 18px;border-radius:999px;background:var(--ink);color:#fff;text-decoration:none;font-weight:700}.entry-card.featured .entry-btn{background:var(--lime)}.entry-note{margin-top:18px;text-align:center;color:var(--gray-2);font-size:13px}
.break-even{padding:80px 24px;background:#fff}.break-even-inner{max-width:900px;margin:0 auto}.break-even-head{text-align:center}.break-even-head h2{font-size:clamp(31px,4.7vw,46px)}.break-even-head p{color:var(--gray-2);margin-top:10px}.be-panel{margin-top:30px;border:1px solid var(--gray-soft);border-radius:26px;padding:30px;background:#fff}.be-control{display:grid;grid-template-columns:1fr 110px;gap:18px;align-items:end}.be-control label{font-weight:650}.be-control input[type=range]{width:100%;margin-top:12px}.be-number{border:1px solid var(--gray-soft);border-radius:14px;padding:12px;text-align:center;font-size:22px;font-weight:700}.be-results{display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px;margin-top:26px}.be-result{background:var(--paper-warm);border-radius:18px;padding:20px}.be-result span{display:block;color:var(--gray-2);font-size:12px}.be-result strong{display:block;font-size:25px;margin-top:4px}.be-result.win{background:#eff8f2}.be-message{margin-top:18px;padding:17px 19px;border-radius:16px;background:#f4f9ff;font-weight:650}.be-message span{color:var(--lime)}
@media(max-width:760px){.proof-strip-inner,.entry-grid{grid-template-columns:1fr}.be-control{grid-template-columns:1fr}.be-results{grid-template-columns:1fr}.proof-strip{padding-top:42px;padding-bottom:42px}}
</style>
'''
if 'proof-strip-inner' not in s:
    s = s.replace('<!-- Microsoft Clarity -->', css + '<!-- Microsoft Clarity -->')

sections = '''<section class="proof-strip" aria-label="Depoimento de cliente">
  <div class="proof-strip-inner">
    <div><div class="proof-kicker">Case real</div><h2>Mais controle depois da venda.</h2></div>
    <div><div class="proof-quote">“Saímos de uma situação de baixo controle para o <strong>controle total da nossa carteira</strong>. Hoje sabemos exatamente o status de cada unidade, cada contrato e cada repasse.”</div><div class="proof-person">Adson Soares · Gestor de Incorporação · NJS Engenharia</div><a class="proof-link" href="./pages/cases/njs-engenharia-credituz.html" data-track="case_njs_home">Ver case completo →</a></div>
  </div>
</section>
<section class="entry-choice" id="comece"><div class="entry-choice-inner"><div class="entry-head"><div class="section-tag">Comece do jeito que faz sentido para sua operação</div><h2>Uma análise avulsa ou a operação completa.</h2><p>Quem consulta ocasionalmente pode começar pelo Credituz Score. Quem analisa clientes todos os meses ganha escala com o Credituz OS.</p></div><div class="entry-grid"><article class="entry-card"><div class="entry-tag">Uso ocasional</div><h3>Credituz Score</h3><div class="entry-price">R$ 27,70 <small>/ análise</small></div><p>Uma análise completa de crédito, sem assinatura e sem mensalidade.</p><ul class="entry-list"><li>Score e sinais de risco</li><li>Renda estimada e parcela máxima</li><li>Restrições, protestos e processos</li><li>Pague apenas quando usar</li></ul><a class="entry-btn" href="./pages/credituz-score.html" data-track="home_score_entry">Fazer uma análise</a></article><article class="entry-card featured"><div class="entry-tag">Uso profissional recorrente</div><h3>Credituz OS</h3><div class="entry-price">R$ 297 <small>/ mês + R$ 16 por análise</small></div><p>Para quem quer analisar clientes, simular, solicitar e acompanhar crédito dentro da mesma operação.</p><ul class="entry-list"><li>CRM de crédito + CORBAN AI</li><li>Análises por R$ 16</li><li>Contratos e cobrança</li><li>Portal e gestão operacional</li></ul><a class="entry-btn" href="https://dashboard.usecredituz.com/auth/login?screen_hint=signup&ref=home-entry-os" target="_blank" rel="noopener" data-track="home_os_entry">Criar minha conta</a></article></div><div class="entry-note">A partir de 26 análises no mês, o plano de R$ 297 já fica mais barato do que comprar todas as análises avulsas — mesmo antes de considerar os demais módulos da plataforma.</div></div></section>
<section class="break-even" id="calculadora-score"><div class="break-even-inner"><div class="break-even-head"><div class="section-tag">Calculadora de economia</div><h2>Quando compensa migrar para o plano?</h2><p>Escolha quantas análises você faz por mês e compare automaticamente.</p></div><div class="be-panel"><div class="be-control"><div><label for="scoreVolume">Análises por mês</label><input id="scoreVolume" type="range" min="1" max="150" value="30" step="1" aria-label="Quantidade de análises por mês"></div><div class="be-number" id="scoreVolumeNumber">30</div></div><div class="be-results"><div class="be-result"><span>Credituz Score avulso</span><strong id="scoreAvulso">R$ 831,00</strong></div><div class="be-result"><span>Plano Credituz OS</span><strong id="scorePlano">R$ 777,00</strong></div><div class="be-result win"><span>Diferença no mês</span><strong id="scoreEconomia">R$ 54,00</strong></div></div><div class="be-message" id="scoreMessage">Com 30 análises, o plano já economiza <span>R$ 54,00/mês</span> e ainda inclui os outros módulos da Credituz.</div></div></div></section>
'''
if 'id="calculadora-score"' not in s:
    anchor = '<section class="showcase"'
    pos = s.find(anchor)
    if pos < 0:
        raise RuntimeError('showcase anchor not found')
    s = s[:pos] + sections + s[pos:]

js = '''<script>
(function(){var input=document.getElementById('scoreVolume');if(!input)return;var n=document.getElementById('scoreVolumeNumber'),av=document.getElementById('scoreAvulso'),pl=document.getElementById('scorePlano'),ec=document.getElementById('scoreEconomia'),msg=document.getElementById('scoreMessage');function brl(v){return v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});}function render(track){var q=Number(input.value),avulso=q*27.70,plano=297+(q*16),diff=Math.abs(avulso-plano);n.textContent=q;av.textContent=brl(avulso);pl.textContent=brl(plano);ec.textContent=brl(diff);if(plano<avulso){msg.innerHTML='Com '+q+' análises, o plano já economiza <span>'+brl(diff)+'/mês</span> e ainda inclui os outros módulos da Credituz.';}else{var falta=Math.max(0,26-q);msg.innerHTML=falta?'Com '+q+' análises, o avulso ainda custa menos. Faltam <span>'+falta+' análise'+(falta===1?'':'s')+'</span> para o plano cruzar o ponto de equilíbrio.':'Você chegou ao <span>ponto de equilíbrio</span> entre as duas opções.';}if(track&&window.dataLayer){window.dataLayer.push({event:'score_break_even_interaction',score_volume:q,score_avulso:avulso,score_plano:plano});}}input.addEventListener('input',function(){render(false)});input.addEventListener('change',function(){render(true)});render(false);})();
</script>'''
if 'score_break_even_interaction' not in s:
    s = s.replace('</body>', js + '</body>')

p.write_text(s, encoding='utf-8')
